[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.5"

[features]
resolution = true
skip-lint = false

[programs.devnet]
registry = "Etr537JjVtMhC6YNj6k2sFd22iCYrVNwnnjif4hXjfTJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
client = "yarn run ts-node client/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
